name: "Dopamine: build_Release"

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: '[ssh-actions]改成[ssh],再按[Run workflow]按钮启动,则开启SSH连接配置固件'
        required: false
        default: 'ssh-actions'  
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  
jobs:
  build:
    runs-on: macos-latest
    environment: Patch AutoBuildRelease
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Procursus
        uses: dhinakg/procursus-action@main
        with:
          packages: ldid trustcache
          
      - name: Install Homebrew
        run: |
          set -x
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install gnu-sed
          brew install make
          
      - name: Install THEOS (without SDKs)
        run: |
          set -x
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          mkdir -p $THEOS
          curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos >> install-theos.sh
          gsed -E "/^\s*get_theos\s*$/,+1 s/^(\s*)(get_sdks)\s*$/\1mkdir -p \${THEOS}\/sdks\n\1touch \${THEOS}\/sdks\/sdk\n\1\2/g" -i install-theos.sh
          bash install-theos.sh
          cd $BASEDIR
      
      - name: Set Environment Variables
        run: |
         sT=$(TZ=UTC-8 date +'%S')
         echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
         echo "shT=$(TZ=UTC-8 date +'%Y.%m.%d/%H.%M').${sT}" >> $GITHUB_ENV
         echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV
         
      - name: Print Environment Variables
        run: |
         echo ${{ env.msT }}
         echo ${{ env.shT }}
         echo ${{ env.logT }} 
         
      - name: Pre code
        run: |
          sed -i '' "s/AAA/${{ env.msT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAB/友情提示: 换盆兑换区已开放兑换/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAC/${{ env.msT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/"opa334"/"MCydia"/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/"opa334"/"MCydia"/g" ./Dopamine/Dopamine/UI/Views/UpdateDownloadingView.swift     
          
      - name: Build
        run: |
          set -x
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          gmake -j$(sysctl -n hw.physicalcpu)
          cp Dopamine/Dopamine.tipa Dopamine.tipa
          mv Dopamine/Dopamine.tipa Dopamine_${{ env.msT }}.tipa       
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:       
          name: ${{ env.shT }}
          tag_name: ${{ env.msT }}
          target_commitish: master
          body_path: ./release.md       
          files: |
           *.tipa
